### ISSUE TITLE
possible ufo2 and ufo3 issue RFont() ?

### ISSUE THREAD

**Issue by jo-lang** [typemytype/drawbot#91]
I am trying to use RFont() in DrawBot 3.94 and get the traceback: 
```
  File "/Volumes/DrawBot/DrawBot.app/Contents/Resources/lib/python2.7/robofab/objects/objectsBase.py", line 184, in __getitem__
AttributeError: 'RFont' object has no attribute 'layers'
```
This did work in version 3.88. 
Thanks, jo

**Comment by typemytype** [comment]
DrawBot moved to UFO3 for all the font related packages...
RoboFab will be removed soon.

you can use fontParts see http://fontparts.readthedocs.io/en/latest/

```
from fontParts.nonelab import RFont
```

**Comment by jo-lang** [comment]
ah, i see! but do not fully understand. 
trying to run 
´´´
from fontParts.nonelab import RFont
´´´
I get an ImportError. (No module named fontParts.nonelab)
So fontParts will replace RoboFab but is not yet built into drawbot? 
Or do I have to install FontParts separately? 
sorry and thanks

**Comment by typemytype** [comment]
oh, I see
fixed 16469746eaaef32568e866e9e9bed81a9c8b5baa

will push a new download
