### ISSUE TITLE
Formatted string issue in latest release

### ISSUE THREAD

**Issue by djrrb** [typemytype/drawbot#35]
Not sure what changed or if I'm doing something wrong, but FYI my scripts with formatted strings in them stopped working after I updated to 3.72 (using the auto-updater).

An example:

f = FormattedString('asdf', font='Verdana')
textBox(f, (0, 0, width(), height()))

Traceback:

Traceback (most recent call last):
  File "<untitled>", line 2, in <module>
  File "drawBot/drawBotDrawingTools.pyc", line 958, in textBox
AttributeError: 'FormattedString' object has no attribute 'decode'

Thanks!

**Comment by typemytype** [comment]
this should be solved in https://github.com/typemytype/drawbot/commit/d61cd98ac12fa4e832510483671090365853ffd0

I didnt post a binary yet, will do today
